/* tslint:disable */

export * from './appProperties.service';
import { AppPropertiesService } from './appProperties.service';
export * from './applicationRoles.service';
import { ApplicationRolesService } from './applicationRoles.service';
export * from './auditRecords.service';
import { AuditRecordsService } from './auditRecords.service';
export * from './avatars.service';
import { AvatarsService } from './avatars.service';
export * from './dashboards.service';
import { DashboardsService } from './dashboards.service';
export * from './dynamicModules.service';
import { DynamicModulesService } from './dynamicModules.service';
export * from './filterSharing.service';
import { FilterSharingService } from './filterSharing.service';
export * from './filters.service';
import { FiltersService } from './filters.service';
export * from './groupAndUserPicker.service';
import { GroupAndUserPickerService } from './groupAndUserPicker.service';
export * from './groups.service';
import { GroupsService } from './groups.service';
export * from './issueAttachments.service';
import { IssueAttachmentsService } from './issueAttachments.service';
export * from './issueCommentProperties.service';
import { IssueCommentPropertiesService } from './issueCommentProperties.service';
export * from './issueComments.service';
import { IssueCommentsService } from './issueComments.service';
export * from './issueCustomFieldOptions.service';
import { IssueCustomFieldOptionsService } from './issueCustomFieldOptions.service';
export * from './issueCustomFieldOptionsApps.service';
import { IssueCustomFieldOptionsAppsService } from './issueCustomFieldOptionsApps.service';
export * from './issueFields.service';
import { IssueFieldsService } from './issueFields.service';
export * from './issueLinkTypes.service';
import { IssueLinkTypesService } from './issueLinkTypes.service';
export * from './issueLinks.service';
import { IssueLinksService } from './issueLinks.service';
export * from './issueNavigatorSettings.service';
import { IssueNavigatorSettingsService } from './issueNavigatorSettings.service';
export * from './issueNotificationSchemes.service';
import { IssueNotificationSchemesService } from './issueNotificationSchemes.service';
export * from './issuePriorities.service';
import { IssuePrioritiesService } from './issuePriorities.service';
export * from './issueProperties.service';
import { IssuePropertiesService } from './issueProperties.service';
export * from './issueRemoteLinks.service';
import { IssueRemoteLinksService } from './issueRemoteLinks.service';
export * from './issueResolutions.service';
import { IssueResolutionsService } from './issueResolutions.service';
export * from './issueSearch.service';
import { IssueSearchService } from './issueSearch.service';
export * from './issueSecurityLevel.service';
import { IssueSecurityLevelService } from './issueSecurityLevel.service';
export * from './issueSecuritySchemes.service';
import { IssueSecuritySchemesService } from './issueSecuritySchemes.service';
export * from './issueTypeProperties.service';
import { IssueTypePropertiesService } from './issueTypeProperties.service';
export * from './issueTypes.service';
import { IssueTypesService } from './issueTypes.service';
export * from './issueVotes.service';
import { IssueVotesService } from './issueVotes.service';
export * from './issueWatchers.service';
import { IssueWatchersService } from './issueWatchers.service';
export * from './issueWorklogProperties.service';
import { IssueWorklogPropertiesService } from './issueWorklogProperties.service';
export * from './issueWorklogs.service';
import { IssueWorklogsService } from './issueWorklogs.service';
export * from './issues.service';
import { IssuesService } from './issues.service';
export * from './jQL.service';
import { JQLService } from './jQL.service';
export * from './jiraExpressions.service';
import { JiraExpressionsService } from './jiraExpressions.service';
export * from './jiraSettings.service';
import { JiraSettingsService } from './jiraSettings.service';
export * from './labels.service';
import { LabelsService } from './labels.service';
export * from './myself.service';
import { MyselfService } from './myself.service';
export * from './permissionSchemes.service';
import { PermissionSchemesService } from './permissionSchemes.service';
export * from './permissions.service';
import { PermissionsService } from './permissions.service';
export * from './projectAvatars.service';
import { ProjectAvatarsService } from './projectAvatars.service';
export * from './projectCategories.service';
import { ProjectCategoriesService } from './projectCategories.service';
export * from './projectComponents.service';
import { ProjectComponentsService } from './projectComponents.service';
export * from './projectKeyAndNameValidation.service';
import { ProjectKeyAndNameValidationService } from './projectKeyAndNameValidation.service';
export * from './projectPermissionSchemes.service';
import { ProjectPermissionSchemesService } from './projectPermissionSchemes.service';
export * from './projectProperties.service';
import { ProjectPropertiesService } from './projectProperties.service';
export * from './projectRoleActors.service';
import { ProjectRoleActorsService } from './projectRoleActors.service';
export * from './projectRoles.service';
import { ProjectRolesService } from './projectRoles.service';
export * from './projectTypes.service';
import { ProjectTypesService } from './projectTypes.service';
export * from './projectVersions.service';
import { ProjectVersionsService } from './projectVersions.service';
export * from './projects.service';
import { ProjectsService } from './projects.service';
export * from './screens.service';
import { ScreensService } from './screens.service';
export * from './serverInfo.service';
import { ServerInfoService } from './serverInfo.service';
export * from './tasks.service';
import { TasksService } from './tasks.service';
export * from './timeTracking.service';
import { TimeTrackingService } from './timeTracking.service';
export * from './userProperties.service';
import { UserPropertiesService } from './userProperties.service';
export * from './userSearch.service';
import { UserSearchService } from './userSearch.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './webhooks.service';
import { WebhooksService } from './webhooks.service';
export * from './workflowSchemeDrafts.service';
import { WorkflowSchemeDraftsService } from './workflowSchemeDrafts.service';
export * from './workflowSchemeProjectAssociations.service';
import { WorkflowSchemeProjectAssociationsService } from './workflowSchemeProjectAssociations.service';
export * from './workflowSchemes.service';
import { WorkflowSchemesService } from './workflowSchemes.service';
export * from './workflowStatusCategories.service';
import { WorkflowStatusCategoriesService } from './workflowStatusCategories.service';
export * from './workflowStatuses.service';
import { WorkflowStatusesService } from './workflowStatuses.service';
export * from './workflowTransitionProperties.service';
import { WorkflowTransitionPropertiesService } from './workflowTransitionProperties.service';
export * from './workflowTransitionRules.service';
import { WorkflowTransitionRulesService } from './workflowTransitionRules.service';
export * from './workflows.service';
import { WorkflowsService } from './workflows.service';
export const APIS = [AppPropertiesService, ApplicationRolesService, AuditRecordsService, AvatarsService, DashboardsService, DynamicModulesService, FilterSharingService, FiltersService, GroupAndUserPickerService, GroupsService, IssueAttachmentsService, IssueCommentPropertiesService, IssueCommentsService, IssueCustomFieldOptionsService, IssueCustomFieldOptionsAppsService, IssueFieldsService, IssueLinkTypesService, IssueLinksService, IssueNavigatorSettingsService, IssueNotificationSchemesService, IssuePrioritiesService, IssuePropertiesService, IssueRemoteLinksService, IssueResolutionsService, IssueSearchService, IssueSecurityLevelService, IssueSecuritySchemesService, IssueTypePropertiesService, IssueTypesService, IssueVotesService, IssueWatchersService, IssueWorklogPropertiesService, IssueWorklogsService, IssuesService, JQLService, JiraExpressionsService, JiraSettingsService, LabelsService, MyselfService, PermissionSchemesService, PermissionsService, ProjectAvatarsService, ProjectCategoriesService, ProjectComponentsService, ProjectKeyAndNameValidationService, ProjectPermissionSchemesService, ProjectPropertiesService, ProjectRoleActorsService, ProjectRolesService, ProjectTypesService, ProjectVersionsService, ProjectsService, ScreensService, ServerInfoService, TasksService, TimeTrackingService, UserPropertiesService, UserSearchService, UsersService, WebhooksService, WorkflowSchemeDraftsService, WorkflowSchemeProjectAssociationsService, WorkflowSchemesService, WorkflowStatusCategoriesService, WorkflowStatusesService, WorkflowTransitionPropertiesService, WorkflowTransitionRulesService, WorkflowsService];
