/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Details of an application property.
 */
export interface ApplicationPropertyModel { 
    /**
     * The ID of the application property. The ID and key are the same.
     */
    id?: string;
    /**
     * The key of the application property. The ID and key are the same.
     */
    key?: string;
    /**
     * The new value.
     */
    value?: string;
    /**
     * The name of the application property.
     */
    name?: string;
    /**
     * The description of the application property.
     */
    desc?: string;
    /**
     * The data type of the application property.
     */
    type?: string;
    /**
     * The default value of the application property.
     */
    defaultValue?: string;
    example?: string;
    /**
     * The allowed values, if applicable.
     */
    allowedValues?: Array<string>;
}

