/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttachmentArchiveItemReadableModel } from './attachmentArchiveItemReadable';


/**
 * Metadata for an archive (for example a zip) and its contents.
 */
export interface AttachmentArchiveMetadataReadableModel { 
    /**
     * The ID of the attachment.
     */
    readonly id?: number;
    /**
     * The name of the archive file.
     */
    readonly name?: string;
    /**
     * The list of the items included in the archive.
     */
    readonly entries?: Array<AttachmentArchiveItemReadableModel>;
    /**
     * The number of items included in the archive.
     */
    readonly totalEntryCount?: number;
    /**
     * The MIME type of the attachment.
     */
    readonly mediaType?: string;
}

