/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDetailsModel } from './userDetails';


/**
 * Details about an attachment.
 */
export interface AttachmentModel { 
  [key: string]: object | any;


    /**
     * The URL of the attachment details response.
     */
    readonly self?: string;
    /**
     * The ID of the attachment.
     */
    readonly id?: string;
    /**
     * The file name of the attachment.
     */
    readonly filename?: string;
    /**
     * Details of the user who added the attachment.
     */
    readonly author?: UserDetailsModel;
    /**
     * The datetime the attachment was created.
     */
    readonly created?: Date;
    /**
     * The size of the attachment.
     */
    readonly size?: number;
    /**
     * The MIME type of the attachment.
     */
    readonly mimeType?: string;
    /**
     * The content of the attachment.
     */
    readonly content?: string;
    /**
     * The URL of a thumbnail representing the attachment.
     */
    readonly thumbnail?: string;
}

