/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssociatedItemBeanModel } from './associatedItemBean';
import { ChangedValueBeanModel } from './changedValueBean';


/**
 * An audit record.
 */
export interface AuditRecordBeanModel { 
    /**
     * The ID of the audit record.
     */
    readonly id?: number;
    /**
     * The summary of the audit record.
     */
    readonly summary?: string;
    /**
     * The URL of the computer where the creation of the audit record was initiated.
     */
    readonly remoteAddress?: string;
    /**
     * Deprecated, use `authorAccountId` instead. The key of the user who created the audit record.
     */
    readonly authorKey?: string;
    /**
     * The date and time on which the audit record was created.
     */
    readonly created?: Date;
    /**
     * The category of the audit record. For a list of these categories, see the help article [Auditing in Jira applications](https://confluence.atlassian.com/x/noXKM).
     */
    readonly category?: string;
    /**
     * The event the audit record originated from.
     */
    readonly eventSource?: string;
    /**
     * The description of the audit record.
     */
    readonly description?: string;
    objectItem?: AssociatedItemBeanModel;
    /**
     * The list of values changed in the record event.
     */
    readonly changedValues?: Array<ChangedValueBeanModel>;
    /**
     * The list of items associated with the changed record.
     */
    readonly associatedItems?: Array<AssociatedItemBeanModel>;
}

