/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A change item.
 */
export interface ChangeDetailsModel { 
    /**
     * The name of the field changed.
     */
    readonly field?: string;
    /**
     * The type of the field changed.
     */
    readonly fieldtype?: string;
    /**
     * The ID of the field changed.
     */
    readonly fieldId?: string;
    /**
     * The details of the original value.
     */
    readonly from?: string;
    /**
     * The details of the original value as a string.
     */
    readonly fromString?: string;
    /**
     * The details of the new value.
     */
    readonly to?: string;
    /**
     * The details of the new value as a string.
     */
    readonly toString?: string;
}

