/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityPropertyModel } from './entityProperty';


/**
 * Details of a changed worklog.
 */
export interface ChangedWorklogModel { 
    /**
     * The ID of the worklog.
     */
    readonly worklogId?: number;
    /**
     * The datetime of the change.
     */
    readonly updatedTime?: number;
    /**
     * Details of properties associated with the change.
     */
    readonly properties?: Array<EntityPropertyModel>;
}

