/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChangedWorklogModel } from './changedWorklog';


/**
 * List of changed worklogs.
 */
export interface ChangedWorklogsModel { 
    /**
     * Changed worklog list.
     */
    readonly values?: Array<ChangedWorklogModel>;
    /**
     * The datetime of the first worklog item in the list.
     */
    readonly since?: number;
    /**
     * The datetime of the last worklog item in the list.
     */
    readonly until?: number;
    /**
     * The URL of this changed worklogs list.
     */
    readonly self?: string;
    /**
     * The URL of the next list of changed worklogs.
     */
    readonly nextPage?: string;
    lastPage?: boolean;
}

