/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegisteredWebhookModel } from './registeredWebhook';


/**
 * Container for a list of registered webhooks. Webhook details are returned in the same order as the request.
 */
export interface ContainerForRegisteredWebhooksModel { 
    /**
     * A list of registered webhooks.
     */
    webhookRegistrationResult?: Array<RegisteredWebhookModel>;
}

