/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NestedResponseModel } from './nestedResponse';


/**
 * Details about a created issue or subtask.
 */
export interface CreatedIssueModel { 
    /**
     * The ID of the created issue or subtask.
     */
    readonly id?: string;
    /**
     * The key of the created issue or subtask.
     */
    readonly key?: string;
    /**
     * The URL of the created issue or subtask.
     */
    readonly self?: string;
    /**
     * The response code and messages related to any requested transition.
     */
    readonly transition?: NestedResponseModel;
}

