/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Details about the replacement for a deleted version.
 */
export interface CustomFieldReplacementModel { 
    /**
     * The ID of the custom field in which to replace the version number.
     */
    customFieldId?: number;
    /**
     * The version number to use as a replacement for the deleted version.
     */
    moveTo?: number;
}

