/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScopeModel } from './scope';


/**
 * Details about a workflow.
 */
export interface DeprecatedWorkflowModel { 
    /**
     * The name of the workflow.
     */
    readonly name?: string;
    /**
     * The description of the workflow.
     */
    readonly description?: string;
    /**
     * The datetime the workflow was last modified.
     */
    readonly lastModifiedDate?: string;
    /**
     * This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.
     */
    readonly lastModifiedUser?: string;
    /**
     * The account ID of the user that last modified the workflow.
     */
    readonly lastModifiedUserAccountId?: string;
    /**
     * The number of steps included in the workflow.
     */
    readonly steps?: number;
    /**
     * The scope where this workflow applies
     */
    readonly scope?: ScopeModel;
    _default?: boolean;
}

