/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A field within a field configuration.
 */
export interface FieldConfigurationItemModel { 
    /**
     * The ID of the field within the field configuration.
     */
    id: string;
    /**
     * The description of the field within the field configuration.
     */
    description?: string;
    /**
     * Whether the field is hidden in the field configuration.
     */
    isHidden?: boolean;
    /**
     * Whether the field is required in the field configuration.
     */
    isRequired?: boolean;
}

