/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPickerUserModel } from './userPickerUser';


/**
 * The list of users found in a search, including header text (Showing X of Y matching users) and total of matched users.
 */
export interface FoundUsersModel { 
    users?: Array<UserPickerUserModel>;
    /**
     * The total number of users found in the search.
     */
    total?: number;
    /**
     * Header text indicating the number of users in the response and the total number of users found in the search.
     */
    header?: string;
}

