/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PagedListUserDetailsApplicationUserModel } from './pagedListUserDetailsApplicationUser';


export interface GroupModel { 
    /**
     * The name of group.
     */
    name?: string;
    /**
     * The URL for these group details.
     */
    readonly self?: string;
    /**
     * A paginated list of the users that are members of the group. A maximum of 50 users is returned in the list, to access additional users append `[start-index:end-index]` to the expand request. For example, to access the next 50 users, use`?expand=users[51:100]`.
     */
    readonly users?: PagedListUserDetailsApplicationUserModel;
    /**
     * Expand options that include additional group details in the response.
     */
    readonly expand?: string;
}

