/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldMetadataModel } from './fieldMetadata';
import { ScopeModel } from './scope';


/**
 * Details of the issue creation metadata for an issue type.
 */
export interface IssueTypeIssueCreateMetadataModel { 
    /**
     * The URL of these issue type details.
     */
    readonly self?: string;
    /**
     * The ID of the issue type.
     */
    readonly id?: string;
    /**
     * The description of the issue type.
     */
    readonly description?: string;
    /**
     * The URL of the issue type\'s avatar.
     */
    readonly iconUrl?: string;
    /**
     * The name of the issue type.
     */
    readonly name?: string;
    /**
     * Indicates whether this issue type is used to create subtasks.
     */
    readonly subtask?: boolean;
    /**
     * The ID of the issue type\'s avatar.
     */
    readonly avatarId?: number;
    /**
     * Unique ID for next-gen projects.
     */
    readonly entityId?: string;
    /**
     * Details of the next-gen projects the issue type is available in.
     */
    readonly scope?: ScopeModel;
    /**
     * Expand options that include additional issue type metadata details in the response.
     */
    readonly expand?: string;
    /**
     * List of the fields available when creating an issue for the issue type.
     */
    readonly fields?: { [key: string]: FieldMetadataModel; };
}

