/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An issue type screen scheme item showing the screen scheme for an issue type.
 */
export interface IssueTypeScreenSchemeItemModel { 
    /**
     * The ID of the issue type screen scheme.
     */
    issueTypeScreenSchemeId: string;
    /**
     * The ID of the issue type or *default*. When set to *default* this issue type screen scheme item applies to all issue types without a screen scheme.
     */
    issueTypeId: string;
    /**
     * The ID of the screen scheme.
     */
    screenSchemeId: string;
}

