/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IssueMatchesForJQLModel } from './issueMatchesForJQL';


/**
 * A list of matched issues or errors for each JQL query, in the order the JQL queries were passed.
 */
export interface IssueMatchesModel { 
    matches: Array<IssueMatchesForJQLModel>;
}

