/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A list of the issues matched to a JQL query or details of errors encountered during matching.
 */
export interface IssueMatchesForJQLModel { 
    /**
     * A list of issue IDs.
     */
    matchedIssues: Array<number>;
    /**
     * A list of errors.
     */
    errors: Array<string>;
}

