/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Details about a syntax error.
 */
export interface JiraExpressionValidationErrorModel { 
    /**
     * The text line in which the error occurred. If absent, the error pertains to the entire expression.
     */
    line?: number;
    /**
     * The text column in which the error occurred. If absent, the error pertains to the entire expression.
     */
    column?: number;
    /**
     * The detailed message about the error.
     */
    message: string;
    /**
     * The error type.
     */
    type: JiraExpressionValidationErrorModel.TypeModelEnum;
}
export namespace JiraExpressionValidationErrorModel {
    export type TypeModelEnum = 'syntax' | 'other';
    export const TypeModelEnum = {
        Syntax: 'syntax' as TypeModelEnum,
        Other: 'other' as TypeModelEnum
    };
}

