/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleLinkModel } from './simpleLink';


/**
 * Details a link group, which defines issue operations.
 */
export interface LinkGroupModel { 
    id?: string;
    styleClass?: string;
    header?: SimpleLinkModel;
    weight?: number;
    links?: Array<SimpleLinkModel>;
    groups?: Array<LinkGroupModel>;
}

