/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationRecipientsModel } from './notificationRecipients';
import { NotificationRecipientsRestrictionsModel } from './notificationRecipientsRestrictions';


/**
 * Details about a notification.
 */
export interface NotificationModel { 
  [key: string]: object | any;


    /**
     * The subject of the email notification for the issue. If this is not specified, then the subject is set to the issue key and summary.
     */
    subject?: string;
    /**
     * The plain text body of the email notification for the issue.
     */
    textBody?: string;
    /**
     * The HTML body of the email notification for the issue.
     */
    htmlBody?: string;
    /**
     * The recipients of the email notification for the issue.
     */
    to?: NotificationRecipientsModel;
    /**
     * Restricts the notifications to users with the specified permissions.
     */
    restrict?: NotificationRecipientsRestrictionsModel;
}

