/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LinkGroupModel } from './linkGroup';


/**
 * Details of the operations that can be performed on the issue.
 */
export interface OperationsModel { 
  [key: string]: object | any;


    /**
     * Details of the link groups defining issue operations.
     */
    readonly linkGroups?: Array<LinkGroupModel>;
}

