/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDetailsModel } from './userDetails';


/**
 * A paged list. To access additional details append `[start-index:end-index]` to the expand request. For example, `?expand=sharedUsers[10:40]` returns a list starting at item 10 and finishing at item 40.
 */
export interface PagedListUserDetailsApplicationUserModel { 
    /**
     * The number of items on the page.
     */
    readonly size?: number;
    /**
     * The list of items.
     */
    readonly items?: Array<UserDetailsModel>;
    /**
     * The maximum number of results that could be on the page.
     */
    readonly maxResults?: number;
    /**
     * The index of the first item returned on the page.
     */
    readonly startIndex?: number;
    /**
     * The index of the last item returned on the page.
     */
    readonly endIndex?: number;
}

