/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParsedJqlQueryModel } from './parsedJqlQuery';


/**
 * A list of parsed JQL queries.
 */
export interface ParsedJqlQueriesModel { 
    /**
     * A list of parsed JQL queries.
     */
    queries: Array<ParsedJqlQueryModel>;
}

