/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ID of a registered webhook or error messages explaining why a webhook wasn\'t registered.
 */
export interface RegisteredWebhookModel { 
    /**
     * The ID of the webhook. Returned if the webhook is created.
     */
    createdWebhookId?: number;
    /**
     * Error messages specifying why the webhook creation failed.
     */
    errors?: Array<string>;
}

