/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationModel } from './application';
import { RemoteObjectModel } from './remoteObject';


/**
 * Details of an issue remote link.
 */
export interface RemoteIssueLinkModel { 
    /**
     * The ID of the link.
     */
    id?: number;
    /**
     * The URL of the link.
     */
    self?: string;
    /**
     * The global ID of the link, such as the ID of the item on the remote system.
     */
    globalId?: string;
    /**
     * Details of the remote application the linked item is in.
     */
    application?: ApplicationModel;
    /**
     * Description of the relationship between the issue and the linked item.
     */
    relationship?: string;
    /**
     * Details of the item linked to.
     */
    object?: RemoteObjectModel;
}

