/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IconModel } from './icon';
import { StatusModel } from './status';


/**
 * The linked item.
 */
export interface RemoteObjectModel { 
  [key: string]: object | any;


    /**
     * The URL of the item.
     */
    url: string;
    /**
     * The title of the item.
     */
    title: string;
    /**
     * The summary details of the item.
     */
    summary?: string;
    /**
     * Details of the icon for the item. If no icon is defined, the default link icon is used in Jira.
     */
    icon?: IconModel;
    /**
     * The status of the item.
     */
    status?: StatusModel;
}

