/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Details of a custom field cascading option to rename.
 */
export interface RenamedCascadingOptionModel { 
    /**
     * The value of the cascading option.
     */
    value: string;
    /**
     * The new value of the cascading option.
     */
    newValue: string;
}

