/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectRoleGroupBeanModel } from './projectRoleGroupBean';
import { ProjectRoleUserBeanModel } from './projectRoleUserBean';


/**
 * Details about a user assigned to a project role.
 */
export interface RoleActorModel { 
    id?: number;
    /**
     * The display name of the user. Depending on the user’s privacy setting, this may return an alternative value.
     */
    readonly displayName?: string;
    type?: string;
    /**
     * This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.
     */
    readonly name?: string;
    avatarUrl?: string;
    actorUser?: ProjectRoleUserBeanModel;
    actorGroup?: ProjectRoleGroupBeanModel;
    user?: string;
}

