/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A screen tab.
 */
export interface ScreenableTabModel { 
    /**
     * The ID of the screen tab.
     */
    readonly id?: number;
    /**
     * The name of the screen tab. The maximum length is 255 characters.
     */
    name: string;
}

