/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RemoveOptionFromIssuesResultModel } from './removeOptionFromIssuesResult';


/**
 * Details about a task.
 */
export interface TaskProgressBeanRemoveOptionFromIssuesResultModel { 
    /**
     * The URL of the task.
     */
    self: string;
    /**
     * The ID of the task.
     */
    id: string;
    /**
     * The description of the task.
     */
    description?: string;
    /**
     * The status of the task.
     */
    status: TaskProgressBeanRemoveOptionFromIssuesResultModel.StatusModelEnum;
    /**
     * Information about the progress of the task.
     */
    message?: string;
    /**
     * The result of the task execution.
     */
    result?: RemoveOptionFromIssuesResultModel;
    /**
     * The ID of the user who submitted the task.
     */
    submittedBy: number;
    /**
     * The progress of the task, as a percentage complete.
     */
    progress: number;
    /**
     * The execution time of the task, in milliseconds.
     */
    elapsedRuntime: number;
    /**
     * A timestamp recording when the task was submitted.
     */
    submitted: number;
    /**
     * A timestamp recording when the task was started.
     */
    started?: number;
    /**
     * A timestamp recording when the task was finished.
     */
    finished?: number;
    /**
     * A timestamp recording when the task progress was last updated.
     */
    lastUpdate: number;
}
export namespace TaskProgressBeanRemoveOptionFromIssuesResultModel {
    export type StatusModelEnum = 'ENQUEUED' | 'RUNNING' | 'COMPLETE' | 'FAILED' | 'CANCEL_REQUESTED' | 'CANCELLED' | 'DEAD';
    export const StatusModelEnum = {
        ENQUEUED: 'ENQUEUED' as StatusModelEnum,
        RUNNING: 'RUNNING' as StatusModelEnum,
        COMPLETE: 'COMPLETE' as StatusModelEnum,
        FAILED: 'FAILED' as StatusModelEnum,
        CANCELREQUESTED: 'CANCEL_REQUESTED' as StatusModelEnum,
        CANCELLED: 'CANCELLED' as StatusModelEnum,
        DEAD: 'DEAD' as StatusModelEnum
    };
}

