/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Counts of the number of issues in various statuses.
 */
export interface VersionIssuesStatusModel { 
  [key: string]: object | any;


    /**
     * Count of issues with a status other than *to do*, *in progress*, and *done*.
     */
    readonly unmapped?: number;
    /**
     * Count of issues with status *to do*.
     */
    readonly toDo?: number;
    /**
     * Count of issues with status *in progress*.
     */
    readonly inProgress?: number;
    /**
     * Count of issues with status *done*.
     */
    readonly done?: number;
}

