/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDetailsModel } from './userDetails';


/**
 * The details of watchers on an issue.
 */
export interface WatchersModel { 
    /**
     * The URL of these issue watcher details.
     */
    readonly self?: string;
    /**
     * Indicates whether the calling user is watching this issue.
     */
    readonly isWatching?: boolean;
    /**
     * The number of users watching this issue.
     */
    readonly watchCount?: number;
    /**
     * Details of the users watching this issue.
     */
    readonly watchers?: Array<UserDetailsModel>;
}

