/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Properties that identify a workflow.
 */
export interface WorkflowIdModel { 
    /**
     * The name of the workflow.
     */
    name: string;
    /**
     * Whether the workflow is in the draft state.
     */
    draft: boolean;
}

