/* tslint:disable */

/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublishedWorkflowIdModel } from './publishedWorkflowId';
import { TransitionModel } from './transition';
import { WorkflowStatusModel } from './workflowStatus';


/**
 * Details about a workflow.
 */
export interface WorkflowModel { 
    id?: PublishedWorkflowIdModel;
    /**
     * The description of the workflow.
     */
    description: string;
    /**
     * The transitions of the workflow.
     */
    transitions?: Array<TransitionModel>;
    /**
     * The statuses of the workflow.
     */
    statuses?: Array<WorkflowStatusModel>;
}

